version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.14

    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Build
          command: go build
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Update submodules
          command: git submodule update --init
      - run:
          name: Run tests
          command: go test ./... -v

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
