name: Build and Test

on:
  - push
  - pull_request

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Get test corpus ETag
      run: >-
        curl https://meta-scrubber-test-corpus.s3.us-west-1.amazonaws.com/exif-image-corpus.tar.gz
        -I | grep -Fi ETag | sed 's/ETag: //g' | tr -d '\r\n' > /tmp/exif-image-corpus-etag
    - name: Cache test corpus
      id: cache-test-corpus
      uses: actions/cache@v3
      with:
        path: |
          testdata/corpus
          testdata/corpus.etag
        key: exif-image-corpus-{{ hashFiles("/tmp/exif-image-corpus-etag") }}
        restore-keys: exif-image-corpus-{{ hashFiles("/tmp/exif-image-corpus-etag") }}
    - name: Download test corpus
      if: steps.cache-test-corpus.outputs.cache-hit != 'true'
      run: |
        curl https://meta-scrubber-test-corpus.s3.us-west-1.amazonaws.com/exif-image-corpus.tar.gz > /tmp/exif-image-corpus.tar.gz
        mkdir -p testdata/corpus
        tar -xzf /tmp/exif-image-corpus.tar.gz -C testdata/corpus
        cp /tmp/exif-image-corpus-etag testdata/corpus.etag
    # n.b. Usually we run the race detector in CI, but for some reason the race detector slows these
    # tests down by a factor of 10 or 100 in GitHub Actions.
    - name: Run unit tests
      run: go test -v -failfast -coverprofile=profile.cov ./...
    - name: Install goveralls
      run: go install github.com/mattn/goveralls@latest
    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=profile.cov -service=github